spring.application.name=techmind

server.port=8080

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/techmind
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

python.api.url=http://localhost:8000